language: go

sudo: required

services:
  - docker

go:
  - 1.5

jobs:
  include:
    - stage: test
      before_install:
        - curl https://glide.sh/get | sed 's+get TAG https://glide.sh/version+TAG=v0.12.3+' | sh
      install:
        - glide install -v
      before_script:
        - make binary-linux-amd64
        - chmod +x bin/linux/amd64/local-persist
        - sudo ./bin/linux/amd64/local-persist &
      script:
        - ./scripts/integration.sh
        - make test

    - &deploy-stage
      stage: build and deploy
      script:
        - docker build -t local-persist:$DOCKER_ARCH --build-arg GOARCH=$DOCKER_GOARCH --build-arg GOARM=$DOCKER_GOARM .
      after_success:
        - |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
          if [ "$TRAVIS_BRANCH" == "master" ]; then
            docker tag local-persist:$DOCKER_ARCH $DOCKER_USER/docker-local-persist-volume-plugin:latest-$DOCKER_ARCH
            docker push $DOCKER_USER/docker-local-persist-volume-plugin:latest-$DOCKER_ARCH
          elif [ -n "$TRAVIS_TAG" ]; then
            docker tag local-persist:$DOCKER_ARCH $DOCKER_USER/docker-local-persist-volume-plugin:$TRAVIS_TAG-$DOCKER_ARCH
            docker push $DOCKER_USER/docker-local-persist-volume-plugin:$TRAVIS_TAG-$DOCKER_ARCH
          fi
      env:
        - DOCKER_ARCH=amd64
        - DOCKER_GOARCH=amd64

    - <<: *deploy-stage
      env:
        - DOCKER_ARCH=arm32v6
        - DOCKER_GOARCH=arm
        - DOCKER_GOARM=6

    - <<: *deploy-stage
      env:
        - DOCKER_ARCH=arm32v7
        - DOCKER_GOARCH=arm
        - DOCKER_GOARM=7

    - <<: *deploy-stage
      env:
        - DOCKER_ARCH=aarch64
        - DOCKER_GOARCH=arm64

    - stage: manifest
      if: branch = master OR tag IS present
      script:
        - export TAG=${TRAVIS_TAG:-latest}
        - export IMAGE_PREFIX=$DOCKER_USER/docker-local-persist-volume-plugin
        - envsubst < manifest.template.yml > manifest.yml
        - echo "$DOCKER_PASSWORD" | docker login --username "${DOCKER_USER}" --password-stdin
        - curl -fsSL https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 > ./manifest-tool
        - chmod +x ./manifest-tool
        - ./manifest-tool push from-spec manifest.yml

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7dc8b1b12ff5bd6c133e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
